nome_do_cliente = input("Digite o nome do cliente: ")
dia_de_vencimento = input("Digite o dia de vencimento: ")
mes_de_vencimento = input("Digite o mês de vencimento: ")
valor_da_fatura = input("Digite o valor da fatura: ")
print("Olá,",nome_do_cliente)
print("A sua fatura com vencimento em",dia_de_vencimento,"de",mes_de_vencimento,"no valor de R$",valor_da_fatura,"está fechada.")